{% set name = "sumo" %}
{% set version = "2.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 944d2569dbf3fe9c05a81fa9042e98e7b349d42d5c00a380f8544b7d1ea8df1d

build:
  number: 0
  entry_points:
    - sumo-bandplot = sumo.cli.bandplot:main
    - sumo-bandstats = sumo.cli.bandstats:main
    - sumo-dosplot = sumo.cli.dosplot:main
    - sumo-kgen = sumo.cli.kgen:main
    - sumo-phonon-bandplot = sumo.cli.phonon_bandplot:main
    - sumo-optplot = sumo.cli.optplot:main
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - monty
    - matplotlib-base
    - numpy
    - phonopy >=2.1.3
    - pymatgen
    - python >=3.8
    - scipy
    - seekpath
    - spglib
    - castepxbin =0.1.0
    - colormath
    - importlib-resources

test:
  imports:
    - sumo
    - sumo.cli
  commands:
    - pip check
    - sumo-bandplot --help
    - sumo-bandstats --help
    - sumo-dosplot --help
    - sumo-kgen --help
    - sumo-phonon-bandplot --help
    - sumo-optplot --help
  requires:
    - pip

about:
  home: https://github.com/SMTG-UCL/sumo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Heavy weight plotting tools for ab initio solid-state calculations

  description: |
    Sumo is a Python toolkit for plotting and analysis of ab initio 
    solid-state calculation data, built on existing Python packages from 
    the solid-state chemistry/physics community. It is hoped that these 
    command-line tools will bring some of the benefits of these libraries 
    to a wider user-base while providing publication-ready plotting 
    (powered by Matplotlib.)
  doc_url: https://sumo.readthedocs.io/en/latest/
  dev_url: https://github.com/SMTG-UCL/sumo

extra:
  recipe-maintainers:
    - jan-janssen
